[package]
name = "memcomparable"
version = "0.1.0"
edition = "2021"
description = "Memcomparable format."
homepage = "https://github.com/risingwavelabs/memcomparable"
repository = "https://github.com/risingwavelabs/memcomparable"
keywords = ["memcomparable"]
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
serde = "1"
thiserror = "1"

[dev-dependencies]
rand = "0.8"
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
